name: accuweather hourly
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 16 * * *'

jobs:
  my-job:
    name: Accuweather Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: generate keys
      run: |
        echo -n '${{ secrets.ACCUWEATHERKEY }}' > accuweatherkey
        echo '''${{ secrets.FIREBASETOKEN }}''' > crawler-practice-firebase-adminsdk-credential.json
    - name: python depancies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python crawl accuweather
      run: |
        python accu_hourly_oneloafofdragon.py