name: openweather daily
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'
jobs:
  my-job:
    name: Openweather Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: generate keys
      run: |
        echo -n '${{ secrets.OPENWEATHERKEY }}' > openweatherkey
        echo '''${{ secrets.FIREBASETOKEN }}''' > crawler-practice-firebase-adminsdk-credential.json
    - name: python depancies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python crawl openweather
      run: |
        python open_daily_oneloafofdragon.py